package com.cgipraktika.reserveerimine;

import com.cgipraktika.reserveerimine.model.TableEntity;
import com.cgipraktika.reserveerimine.model.TableFeature;
import com.cgipraktika.reserveerimine.repository.TableRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.Set;

@SpringBootApplication
public class ReserveerimineApplication {

    private static final Logger logger = LoggerFactory.getLogger(ReserveerimineApplication.class);

    public static void main(String[] args) {
        SpringApplication.run(ReserveerimineApplication.class, args);
    }

    // Test data has been generated by AI.

    @Bean
    public CommandLineRunner demo(TableRepository repository) {
        return (args) -> {
            // Clear existing data to avoid duplicates on restart (if using a persistent DB)
            repository.deleteAll();

            // 1. A cozy window table for 2
            repository.save(TableEntity.builder()
                    .seats(2)
                    .zone("Main Hall")
                    .features(Set.of(TableFeature.WINDOW, TableFeature.PRIVATE))
                    .build());

            // 2. A large family table near the kids zone
            repository.save(TableEntity.builder()
                    .seats(8)
                    .zone("Family Area")
                    .features(Set.of(TableFeature.KIDS_ZONE, TableFeature.ACCESSIBLE))
                    .build());

            // 3. A terrace table
            repository.save(TableEntity.builder()
                    .seats(4)
                    .zone("Terrace")
                    .features(Set.of(TableFeature.TERRACE))
                    .build());

            // 4. An occupied table (to test your 'available' filter)
            repository.save(TableEntity.builder()
                    .seats(4)
                    .zone("Main Hall")
                    .occupied(true)
                    .features(Set.of(TableFeature.WINDOW))
                    .build());

            logger.info("Database seeded with 4 test tables.");

            // Log everything to the console for verification
            repository.findAll().forEach(table -> logger.info("Seeded: {}", table));
        };
    }
}